### PR TITLE
Make sure Router is used in MainActor

### LINKED ISSUE #513: discoverPath causes the app to crash
I cannot explain it why yet. We have several crashes that ocur in the getter and setter.

### PR DESCRIPTION
**Pull request by martindsq**
Closes #513 

We cannot technically close 513 as we don't know the underlying issue for sure, but lets close it for the moment and open it again if we see the same crash in the next builds

### CODE REVIEW

**Comment by martindsq** [comment]
The changelog entry is not very informative for the user, but could help us identify if this causes issues in future builds because the Router is used everywhere

File: Nos/Views/Onboarding/OnboardingLoginView.swift [hunk 1]
```diff
@@ -10,7 +10,7 @@ import Dependencies
 import Logger
 
 struct OnboardingLoginView: View {
-    var completion: () -> Void
+    let completion: @MainActor () -> Void
```
Comment (mplorentz) [inline Nos/Views/Onboarding/OnboardingLoginView.swift:13]: Oh I didn't know you could annotate a closure type this way. Cool.

**Review by mplorentz — APPROVED** [review]

File: Nos/Views/Onboarding/OnboardingLoginView.swift (hunk 1 above)
Comment (martindsq) [reply Nos/Views/Onboarding/OnboardingLoginView.swift:13]: Yeah, just tried and it worked. It was the only chance we had to not lose the mainactor in the onboarding completions
