### PR TITLE
Fixed "replied" header on NoteCard 

### LINKED ISSUE #213: "posted" vs "replied" header on NoteCard always says "posted"

### PR DESCRIPTION
**Pull request by mplorentz**
and added code to download the replied-to event from relays. Closes #213

### CODE REVIEW

File: Nos/Models/Event+CoreDataClass.swift [hunk 1]
```diff
@@ -728,11 +728,18 @@ public class Event: NosManagedObject {
...
     
     var isReply: Bool {
-        rootNote() != nil
+        rootNote() != nil || referencedNote() != nil
     }
     
     /// Returns the event this note is directly replying to, or nil if there isn't one.
     func referencedNote() -> Event? {
+        if let rootReference = eventReferences?.first(where: {
+            ($0 as? EventReference)?.marker ?? "" == "reply"
```
Comment (martindsq) [inline Nos/Models/Event+CoreDataClass.swift:737]: I think it would be better to make an enum inside Event with some values the marker can take, like root and reply, and use that value here and in other queries we make (they are easily found by searching marker in the project). That way we control the values somewhere and make it easy for other developers to find out what marker usually means.

**Review by martindsq — CHANGES_REQUESTED** [review]

File: Nos/Models/Event+CoreDataClass.swift (hunk 1 above)
Comment (mplorentz) [reply Nos/Models/Event+CoreDataClass.swift]: Good idea. I cleaned this up.

**Review by martindsq — APPROVED** [review]
