### PR TITLE
Fix #1387: After navigating back to Feed, scroll position is lost

### LINKED ISSUE #1387: [Bug] After navigating back to Feed, the scroll position is lost
## Describe the bug
After navigating back to Feed, the scroll position is lost. You're back at the top of the Feed even if you had scrolled down.

## To Reproduce
1. Go to Feed
2. Scroll down
3. Tap a note to see the Thread view
4. Tap Back to go back to Feed
5. Observe that your scroll position is lost and you're back at the top of the Feed

## Expected behavior
The position you left the Feed is where you should return when you tap Back from a Thread view.

## Screenshots or Video
https://github.com/user-attachments/assets/534d9eb9-60c4-481a-890c-f20aaa886bdc

## Technical info
 - OS: iOS, macOS, probably iPadOS
 - App Version: `main`, Staging 0.1.24 (395). Does not happen in Staging 0.1.24 (393) or (394).
 - Environment: all

## Additional context
https://planetary-app.slack.com/archives/CM4EPK324/p1722988478837649

From Matt:

> I bet the PagedNoteListView.updateUIView() is firing and we are reloadingData on the collectionView.

### PR DESCRIPTION
**Pull request by joshuatbrown**
## Issues covered
#1387

## Description
The `lastRefreshDate` was `nil` and therefore the `homeFeedFetchRequest` was constantly being updated. Whenever the fetch request is updated, the view scrolls to the top (probably/maybe through a `reloadData()` on the collection view).

## How to test
1. Go to Feed
2. Scroll down
3. Tap a note to see the Thread view
4. Tap Back to go back to Feed
5. Observe that your scroll position is maintained

## Screenshots/Video
https://github.com/user-attachments/assets/638c4525-ef23-4372-8d2f-0677da263d66

## Additional Information
I'm skipping the CHANGELOG on this one since we didn't release the bug (which was introduced when we merged #1370), so users might be confused if they see the fix in the release notes. I suppose I could add it to the CHANGELOG and then make sure it's not in the external release notes. Open to suggestions on this.

### CODE REVIEW

File: Nos/Views/Home/HomeFeedView.swift [hunk 1]
```diff
@@ -11,7 +11,9 @@ struct HomeFeedView: View {
     @Environment(CurrentUser.self) var currentUser
     @ObservationIgnored @Dependency(\.analytics) private var analytics
 
-    @State private var refreshController: RefreshController = DefaultRefreshController()
+    @State private var refreshController: RefreshController = DefaultRefreshController(
+        lastRefreshDate: Date(timeIntervalSince1970: Date.now.timeIntervalSince1970 + Double(Self.staticLoadTime))
```
Comment (martindsq) [inline Nos/Views/Home/HomeFeedView.swift:15]: TimeInterval is a type alias for Double, so there is no need to cast it. Also, it would be more succinct to just do:
`lastRefreshDate: Date.now + Self.staticLoadTime`

File: Nos/Controller/RefreshController.swift [hunk 2]
```diff
@@ -19,9 +19,9 @@ import Foundation
 @Observable @MainActor class DefaultRefreshController: RefreshController {
     var shouldRefresh: Bool
 
-    var lastRefreshDate: Date?
+    var lastRefreshDate: Date
 
-    init(shouldRefresh: Bool = false, lastRefreshDate: Date? = nil) {
+    init(shouldRefresh: Bool = false, lastRefreshDate: Date = .now) {
```
Comment (martindsq) [inline Nos/Controller/RefreshController.swift:24]: I know you are adding comments in the other PRs, so I'm not asking to add doc comments here.

**Review by martindsq — CHANGES_REQUESTED** [review]
It almost mergeable, just asked one stylistic change before giving the green light.

File: Nos/Views/Home/HomeFeedView.swift (hunk 1 above)
Comment (joshuatbrown) [reply Nos/Views/Home/HomeFeedView.swift:15]: I think I just copied what used to be here but you're right. I'll fix it.

File: Nos/Controller/RefreshController.swift (hunk 2 above)
Comment (joshuatbrown) [reply Nos/Controller/RefreshController.swift:24]: Yeah, I'll add docs in my next PR. It's almost ready.

Comment (joshuatbrown) [reply Nos/Controller/RefreshController.swift:24]: Actually, I just realized it is ready, and there are docs in it. #1389

**Review by martindsq — APPROVED** [review]
