### PR TITLE
Increased the size of the NoteOptionsButton

### LINKED ISSUE #287: Can't access note options on the note view
At the moment you can only access the three dot settings from the list view of posts but not from the card for a specific note. 

This is a regression bug i believe. It might be related to #284 which is another bug that you can't click on images or links within the note card. 

Screenshot 2023-05-01 at 9 55 29 AM
ED611D6A-8AF3-4688-8938-49D387A5DB91_1_201_a

### PR DESCRIPTION
**Pull request by mplorentz**
Closes #287

### CODE REVIEW

**Comment by mplorentz** [comment]
looks like the timestamps are now way offset from the ellipsis button on the iPhone. I'll fix that tomorrow.

File: Nos/Views/NoteOptionsButton.swift [hunk 1]
```diff
@@ -27,8 +27,11 @@ struct NoteOptionsButton: View {
             Button {
                 showingOptions = true
             } label: {
-                Image(systemName: "ellipsis")
-                    .foregroundColor(.nosSecondary)
+                VStack {
```
Comment (martindsq) [inline Nos/Views/NoteOptionsButton.swift:30]: There shouldn't be a need to add a VStack here. Just adding `.frame(minWidth: 44, minHeight: 44)` to `Image` seems to do the work in my tests.

**Review by martindsq — CHANGES_REQUESTED** [review]

**Review by martindsq — APPROVED** [review]
