### PR TITLE
Track socket status

### LINKED ISSUE #1308: Sending duplicate requests to the same relay
While debugging the RelayService I discovered that we are sending duplicate subscription requests on a single websocket. This causes congestion in our communication with relays and will slow down the app and sometimes cause things to fail to load.

### PR DESCRIPTION
**Pull request by mplorentz**
## Issues covered
This is the foundation for adding NIP-42 auth support for #1325 / #1311, but also happens to fix #1308 too.

## Description
In order to support NIP-42 auth we need to be able to detech `AUTH` messages from the relay, respond to them, and then re-send our requests. To do this we need to put the relay connection in a sort of suspended state where we aren't slamming it with requests while the authentication flow finishes. And we need to detect when it comes out of this state so that we can resubmit our requests.

This PR adds a `WebSocketConnection` class with a `state` variable that we can use to see where a given `WebSocket` is. Right now it doesn't do auth but models the other states we were doing a poor job of keeping track of before: `disconnected`, `connecting`, `connected`, and `errored`.

To track these states I moved the responsibility of opening sockets from the `RelayService` into the `RelaySubscriptionManager`. Now the `RelayService` does less with sockets, and is mostly just responsible for handling the messages that come from them (someday maybe it can not even know about sockets and just handle the messages? idk. But responsibilities are still too muddy here.) The `RelaySubscriptionManager` takes care of 
1. figuring out what sockets we need to open based on the `RelaySubscriptions` other systems have asked 
2. opening those sockets
3. updating their state based on events that happen in the `RelayService` like connections or errors

Because we are tracking this in a more airtight manner we no longer have race conditions where we open multiple sockets for the same relay which is #1308. 

## How to test
This is a tough one, and not least because there are a bunch of other bugs in the app right now so it's hard to tell what PR is fixing what. But generally there should be no functional change from `main`. In general stuff should load (but sometimes doesn't because of #1322 #1323 #1324 ugh).

To test the fix for #1308 specifically I would put a breakpoint somewhere like the `processSubscriptionQueue` function and print out all the `socketConnections`'s socket memory addresses and URLs and make sure there aren't multiple sockets for one URL.

### CODE REVIEW

**Comment by mplorentz** [comment]
@joshuatbrown 👍 done

File: Nos/Service/Relay/RelaySubscriptionManager.swift [hunk 1]
```diff
@@ -270,28 +300,48 @@ actor RelaySubscriptionManagerActor: RelaySubscriptionManager {
...
+            requestEvents(from: connection.socket, subscription: subscription)
+        }
+        processSubscriptionQueue()
     }
 }
 
 /// A container that tracks how many times we have tried unsuccessfully to open a websocket and the next time we should
 /// try again.
-fileprivate struct WebsocketErrorEvent {
+struct WebSocketErrorEvent: Equatable {
```
Comment (joshuatbrown) [inline Nos/Service/Relay/RelaySubscriptionManager.swift:344]: I generally prefer smaller files, so I'd love to see this struct and everything below in a separate file. One hidden benefit: smaller files make PR reviews easier since I do them one file at a time and check the "Viewed" box once I'm good with a file.

File: Nos/Service/Relay/RelaySubscriptionManager.swift [hunk 2]
```diff
@@ -52,9 +54,15 @@ actor RelaySubscriptionManagerActor: RelaySubscriptionManager {
     func all() async -> [RelaySubscription] {
         all
     }
-
-    func sockets() async -> [WebSocket] {
-        sockets
+    
+    // MARK: - Init
```
Comment (joshuatbrown) [inline Nos/Service/Relay/RelaySubscriptionManager.swift:58]: What does `Init` mean here? I was expecting to see an initializer and found none.

File: Nos/Service/Relay/RelaySubscriptionManager.swift [hunk 3]
```diff
@@ -114,58 +122,90 @@ actor RelaySubscriptionManagerActor: RelaySubscriptionManager {
...
-        guard !sockets.contains(where: { $0.request.url == relayAddress }) else {
-            return nil
-        }
-        
-        if let priorError = errored[relayAddress],
-            priorError.nextRetry > Date.now {
-            // This socket has errored recently and it isn't yet time to retry again.
-            return nil
+        for relayAddress in relayAddresses {
+            var connection: WebSocketConnection
```
Comment (joshuatbrown) [inline Nos/Service/Relay/RelaySubscriptionManager.swift:134]:
```suggestion
            let connection: WebSocketConnection
```

File: Nos/Service/Relay/RelaySubscriptionManager.swift [hunk 4]
```diff
@@ -114,58 +122,90 @@ actor RelaySubscriptionManagerActor: RelaySubscriptionManager {
...
+                connection.state = .connecting
+            case .connected, .connecting:
+                return
+            }
         }
-        
+    }
+    
+    /// Creates a WebSocketConnection for a relay. This is not idempotent - make sure it's called only once for 
+    /// each relay.
```
Comment (joshuatbrown) [inline Nos/Service/Relay/RelaySubscriptionManager.swift:158]: What happens if it's called more than once per relay? It looks like we'd replace the old connection with a new one in the dictionary, maybe? Could we make it idempotent, or is there a reason not to?

File: Nos/Service/Relay/RelaySubscriptionManager.swift [hunk 5]
```diff
@@ -114,58 +122,90 @@ actor RelaySubscriptionManagerActor: RelaySubscriptionManager {
...
-            return sockets[index]
-        }
-        return nil
+        socketConnections[url]?.socket
     }
     
     // MARK: - Talking to Relays
     
-    func processSubscriptionQueue() async {
+    /// This function looks at the current state of sockets and subscriptions and opens new ones. It includes logic to
```
Comment (joshuatbrown) [inline Nos/Service/Relay/RelaySubscriptionManager.swift:202]:
```suggestion
    /// Looks at the current state of sockets and subscriptions and opens new ones. It includes logic to 
```

File: Nos/Service/Relay/RelaySubscriptionManager.swift [hunk 6]
```diff
@@ -303,3 +353,21 @@ fileprivate struct WebsocketErrorEvent {
...
+        self.socket = socket
+        self.state = state
+    }
+}
+
+/// The states a WebSocketConnection can be in. These states are used by `RelaySubscriptionManager` to move each 
+/// socket to the `connected` state where we can start executing requests, taking into account time to connect, errors
+/// and authentication.
+enum WebSocketState: Equatable {
+    case disconnected, connecting, connected, errored(WebSocketErrorEvent)
```
Comment (joshuatbrown) [inline Nos/Service/Relay/RelaySubscriptionManager.swift:372]: I don't love the name `errored` but maybe it's because I don't know WebSockets all that well. I like `error` or `failed` but maybe those don't make sense here.

**Review by joshuatbrown — CHANGES_REQUESTED** [review]
Works well and seems to fix the bug.

File: Nos/Service/Relay/RelaySubscriptionManager.swift (hunk 2 above)
Comment (mplorentz) [reply Nos/Service/Relay/RelaySubscriptionManager.swift:58]: Oops, I had an `init` here at one point but removed it and forgot to remove the `MARK`.

File: Nos/Service/Relay/RelaySubscriptionManager.swift (hunk 4 above)
Comment (mplorentz) [reply Nos/Service/Relay/RelaySubscriptionManager.swift:158]: If it's called more than once then we will leave dangling WebSockets open that won't close until the app is closed. 

I think I could make it idempotent though with some refactoring to `openSockets()` - I'll try that.

File: Nos/Service/Relay/RelaySubscriptionManager.swift (hunk 6 above)
Comment (mplorentz) [reply Nos/Service/Relay/RelaySubscriptionManager.swift:372]: 🤔 I like "error" in the past tense because it matches "disconnected" and "connected". It's saying "this socket has closed on an error in the past". Does that help? I could add some doc comments to it.

Comment (joshuatbrown) [reply Nos/Service/Relay/RelaySubscriptionManager.swift]: Yeah, I thought that might be the thinking. I'd love doc comments for each case.

**Review by joshuatbrown — APPROVED** [review]
This is amazing! I love the added docs!

File: Nos/Service/Relay/RelaySubscriptionManager.swift (hunk 6 above)
Comment (joshuatbrown) [reply Nos/Service/Relay/RelaySubscriptionManager.swift]: Oh, you already did. Thanks!

File: Nos/Service/Relay/RelaySubscriptionManager.swift (hunk 4 above)
Comment (joshuatbrown) [reply Nos/Service/Relay/RelaySubscriptionManager.swift:151]: @mplorentz did you end up doing this? I approved and am good with it either way -- just want to know.
