### PR TITLE
fixing it so displays post button on mac when writing a reply Fixes #584

### LINKED ISSUE #584: Bug, not way to submit longer comments on Nos in macos
If you write more than a few lines in mac nos there's not way to submit it and post. 

Screenshot 2023-10-03 at 12 28 38 PM

### PR DESCRIPTION
**Pull request by rabble**
#584

### CODE REVIEW

File: Nos/Views/ExpandingTextFieldAndSubmitButton.swift [hunk 1]
```diff
@@ -24,35 +24,41 @@ struct ExpandingTextFieldAndSubmitButton: View {
...
-                        Localized.post.view
+                        Localized.post.view // Ensure 'Localized' is defined elsewhere
                     }
                 )
                 .disabled(disabled)
             }
         }
-        .onChange(of: focus.wrappedValue) { bool in
-            showPostButton = bool
+        .onChange(of: reply) { newText in
```
Comment (mplorentz) [inline Nos/Views/ExpandingTextFieldAndSubmitButton.swift:49]: I think this block is the one that actually fixed the bug. Can you try reverting all the other changes?

Comment (mplorentz) [reply Nos/Views/ExpandingTextFieldAndSubmitButton.swift:49]: I did it.

**Review by mplorentz — APPROVED** [review]
